// <auto-generated />
using System;
using CompanyPosts.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyPosts.Infrastructure.Migrations
{
    [DbContext(typeof(CompanyPostDbContext))]
    [Migration("20250917150013_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CompanyPosts.Domain.Entities.Contracts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Attachments")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("attachments");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contract_number");

                    b.Property<DateTime>("Contract_Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("contract_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("Currency")
                        .HasColumnType("int")
                        .HasColumnName("currency");

                    b.Property<DateTime>("DateOfDelivery")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_of_delivery");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("details");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PersonOrgFromId")
                        .HasColumnType("char(36)")
                        .HasColumnName("person_org_from_id");

                    b.Property<Guid>("PersonOrgPreparedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("person_org_prepared_by_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("project_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("PersonOrgFromId")
                        .HasDatabaseName("ix_contracts_person_org_from_id");

                    b.HasIndex("PersonOrgPreparedById")
                        .HasDatabaseName("ix_contracts_person_org_prepared_by_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_contracts_project_id");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("CompanyPosts.Domain.Entities.DeliveryMethods", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_delivery_methods");

                    b.ToTable("delivery_methods", (string)null);
                });

            modelBuilder.Entity("CompanyPosts.Domain.Entities.PersonOrg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("address");

                    b.Property<string>("Contact_Person")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contact_person");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("SAP_BP")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sap_bp");

                    b.HasKey("Id")
                        .HasName("pk_person_orgs");

                    b.HasAlternateKey("SAP_BP")
                        .HasName("ak_person_orgs_sap_bp");

                    b.ToTable("person_orgs", (string)null);
                });

            modelBuilder.Entity("CompanyPosts.Domain.Entities.PostHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_post_headers");

                    b.ToTable("post_headers", (string)null);
                });

            modelBuilder.Entity("CompanyPosts.Domain.Entities.PostTypes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PostId")
                        .HasColumnType("char(36)")
                        .HasColumnName("post_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_post_types");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_post_types_post_id");

                    b.ToTable("post_types", (string)null);
                });

            modelBuilder.Entity("CompanyPosts.Domain.Entities.Posts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Attachment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("attachment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("DateOfDelivery")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_of_delivery");

                    b.Property<DateTime>("DateOfPost")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_of_post");

                    b.Property<Guid>("DeliveryMethodId")
                        .HasColumnType("char(36)")
                        .HasColumnName("delivery_method_id");

                    b.Property<Guid>("DeliveryPersonId")
                        .HasColumnType("char(36)")
                        .HasColumnName("delivery_person_id");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("document_number");

                    b.Property<Guid>("PostOriginalSenderId")
                        .HasColumnType("char(36)")
                        .HasColumnName("post_original_sender_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_posts");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_posts_created_by_id");

                    b.HasIndex("DeliveryMethodId")
                        .HasDatabaseName("ix_posts_delivery_method_id");

                    b.HasIndex("DeliveryPersonId")
                        .HasDatabaseName("ix_posts_delivery_person_id");

                    b.HasIndex("PostOriginalSenderId")
                        .HasDatabaseName("ix_posts_post_original_sender_id");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("CompanyPosts.Domain.Entities.Projects", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("CompanyPosts.Domain.Entities.SysUsers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_sys_users");

                    b.ToTable("sys_users", (string)null);
                });

            modelBuilder.Entity("CompanyPosts.Domain.Entities.Contracts", b =>
                {
                    b.HasOne("CompanyPosts.Domain.Entities.PersonOrg", "PersonOrgFrom")
                        .WithMany("ContractsPersonOrgFrom")
                        .HasForeignKey("PersonOrgFromId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_person_orgs_person_org_from_id");

                    b.HasOne("CompanyPosts.Domain.Entities.PersonOrg", "PersonOrgPreparedBy")
                        .WithMany("ContractsPersonOrgPreparedBy")
                        .HasForeignKey("PersonOrgPreparedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_person_orgs_person_org_prepared_by_id");

                    b.HasOne("CompanyPosts.Domain.Entities.Projects", "Projects")
                        .WithMany("Contracts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_projects_project_id");

                    b.Navigation("PersonOrgFrom");

                    b.Navigation("PersonOrgPreparedBy");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("CompanyPosts.Domain.Entities.PostTypes", b =>
                {
                    b.HasOne("CompanyPosts.Domain.Entities.PostHeader", "PostHeader")
                        .WithMany("PostTypes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_types_post_headers_post_id");

                    b.Navigation("PostHeader");
                });

            modelBuilder.Entity("CompanyPosts.Domain.Entities.Posts", b =>
                {
                    b.HasOne("CompanyPosts.Domain.Entities.SysUsers", "CreatedBy")
                        .WithMany("Posts")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_posts_sys_users_created_by_id");

                    b.HasOne("CompanyPosts.Domain.Entities.DeliveryMethods", "DeliveryMethods")
                        .WithMany("Posts")
                        .HasForeignKey("DeliveryMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_posts_delivery_methods_delivery_method_id");

                    b.HasOne("CompanyPosts.Domain.Entities.PersonOrg", "DeliveryPersons")
                        .WithMany("PostsAsDeliveryPerson")
                        .HasForeignKey("DeliveryPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_posts_person_orgs_delivery_person_id");

                    b.HasOne("CompanyPosts.Domain.Entities.PersonOrg", "PostOriginalSenders")
                        .WithMany("PostsAsOriginalSender")
                        .HasForeignKey("PostOriginalSenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_posts_person_orgs_post_original_sender_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeliveryMethods");

                    b.Navigation("DeliveryPersons");

                    b.Navigation("PostOriginalSenders");
                });

            modelBuilder.Entity("CompanyPosts.Domain.Entities.DeliveryMethods", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("CompanyPosts.Domain.Entities.PersonOrg", b =>
                {
                    b.Navigation("ContractsPersonOrgFrom");

                    b.Navigation("ContractsPersonOrgPreparedBy");

                    b.Navigation("PostsAsDeliveryPerson");

                    b.Navigation("PostsAsOriginalSender");
                });

            modelBuilder.Entity("CompanyPosts.Domain.Entities.PostHeader", b =>
                {
                    b.Navigation("PostTypes");
                });

            modelBuilder.Entity("CompanyPosts.Domain.Entities.Projects", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("CompanyPosts.Domain.Entities.SysUsers", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
